version: "3.5"

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    ports:
      - "10000:10000"
      - "10001:10001"
    volumes:
      - ./az-lazy.test/azurite:/data
    networks:
      - az-lazy-nt

networks:
    az-lazy-nt:
        name: az-lazy-nt
